spring:
  profiles:
    include: dao
  application:
    name: falcon
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
server:
  port: 8080
  servlet:
    context-path: /falcon


